name: 'k6-playground'

on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        filename: [ stages-test, thresholds-test ]
    steps:
      - uses: actions/checkout@v3
      - name: Run ${{ matrix.filename }}
        uses: grafana/k6-action@v0.2.0
        with:
          filename: ${{ matrix.filename }}.js
          cloud: true
          token: ${{ secrets.K6_CLOUD_API_TOKEN }}
#      - name: Upload performance test results
#        uses: actions/upload-artifact@v3
#        with:
#          name: ${{ matrix.filename }}
#          path: ${{ matrix.filename }}.html
